/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.dombosco.dbcode.requisitos.view;

import br.edu.dombosco.dbcode.requisitos.controller.RequisitosController;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;

@Slf4j
/**
 *
 * @author fabio
 */
public class FrameTest extends javax.swing.JFrame {

    @Autowired
    private RequisitosController requisitosController;

    /**
     * Creates new form NewJFrame
     */
    public FrameTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldTittle = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        especificationField = new javax.swing.JTextField();
        ucField = new javax.swing.JTextField();
        findFiend = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        saveButon = new javax.swing.JButton();
        functional = new javax.swing.JCheckBox();
        notFunctionl = new javax.swing.JCheckBox();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Requisitos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 760, 250);

        jLabel2.setText("Nome/Titulo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 18);

        jLabel3.setText("Descrição");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 90, 18);

        fieldTittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTittleActionPerformed(evt);
            }
        });
        jPanel1.add(fieldTittle);
        fieldTittle.setBounds(110, 20, 650, 24);

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        jScrollPane3.setViewportView(textAreaDescription);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(110, 70, 274, 96);

        jButton1.setText("Arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 70, 100, 24);

        jButton2.setText("Arquivo");
        jPanel1.add(jButton2);
        jButton2.setBounds(400, 140, 100, 24);
        jPanel1.add(especificationField);
        especificationField.setBounds(520, 70, 240, 24);
        jPanel1.add(ucField);
        ucField.setBounds(520, 140, 240, 24);

        findFiend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFiendActionPerformed(evt);
            }
        });
        jPanel1.add(findFiend);
        findFiend.setBounds(20, 250, 650, 24);

        findButton.setText("Buscar");
        jPanel1.add(findButton);
        findButton.setBounds(680, 250, 90, 24);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 780, 310);

        jLabel4.setText("Qualificação");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 200, 90, 20);

        saveButon.setText("Salvar");
        jPanel1.add(saveButon);
        saveButon.setBounds(670, 200, 90, 24);

        functional.setText("Funcional");
        jPanel1.add(functional);
        functional.setBounds(100, 200, 110, 22);

        notFunctionl.setText("Não FIncional");
        jPanel1.add(notFunctionl);
        notFunctionl.setBounds(260, 200, 140, 22);

        editButton.setText("Editar");
        jPanel1.add(editButton);
        editButton.setBounds(230, 560, 80, 24);

        removeButton.setText("Excluir");
        jPanel1.add(removeButton);
        removeButton.setBounds(370, 560, 90, 24);

        printButton.setText("Imprimir");
        jPanel1.add(printButton);
        printButton.setBounds(520, 560, 100, 24);

        jLabel5.setText("Anexar Desenho UC");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 120, 140, 18);

        jLabel6.setText("Anexar Especificação");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 50, 180, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backend_opaco.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        Requisitos.setText("File");
        jMenuBar1.add(Requisitos);
        Requisitos.getAccessibleContext().setAccessibleName("Requisitos");

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);
        jMenu2.getAccessibleContext().setAccessibleName("Test");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldTittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTittleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTittleActionPerformed

    private void findFiendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFiendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findFiendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Requisitos;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField especificationField;
    private javax.swing.JTextField fieldTittle;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findFiend;
    private javax.swing.JCheckBox functional;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JCheckBox notFunctionl;
    private javax.swing.JButton printButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButon;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField ucField;
    // End of variables declaration//GEN-END:variables
}
