/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.dombosco.dbcode.requisitos.view;

import br.edu.dombosco.dbcode.requisitos.controller.ProjetosController;

/**
 *
 * @author user
 */
public class ProjetosView extends javax.swing.JPanel {

    /**
     * Creates new form F_Projetos
     */
    public ProjetosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        l_Titulo = new javax.swing.JLabel();
        l_Descricao = new javax.swing.JLabel();
        l_Participantes = new javax.swing.JLabel();
        l_DataInicio = new javax.swing.JLabel();
        l_DataFim = new javax.swing.JLabel();
        l_Estimativas = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        txt_datainicio = new javax.swing.JTextField();
        txt_datafim = new javax.swing.JTextField();
        txt_estimativas = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_particpantes = new javax.swing.JTextArea();
        bt_salvar = new javax.swing.JToggleButton();
        bt_sair = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(936, 600));

        l_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        l_Titulo.setText("NOME/TITULO");

        l_Descricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_Descricao.setForeground(new java.awt.Color(255, 255, 255));
        l_Descricao.setText("DESCRIÇÃO");

        l_Participantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_Participantes.setForeground(new java.awt.Color(255, 255, 255));
        l_Participantes.setText("PARTICIPANTES");

        l_DataInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_DataInicio.setForeground(new java.awt.Color(255, 255, 255));
        l_DataInicio.setText("DATA INICIO");

        l_DataFim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_DataFim.setForeground(new java.awt.Color(255, 255, 255));
        l_DataFim.setText("DATA FIM");

        l_Estimativas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_Estimativas.setForeground(new java.awt.Color(255, 255, 255));
        l_Estimativas.setText("ESTIMATIVAS EM HORAS");

        txt_titulo.setBackground(new java.awt.Color(255, 255, 255));
        txt_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(0, 0, 0));
        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        txt_datainicio.setBackground(new java.awt.Color(255, 255, 255));
        txt_datainicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_datainicio.setForeground(new java.awt.Color(0, 0, 0));
        txt_datainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datainicioActionPerformed(evt);
            }
        });

        txt_datafim.setBackground(new java.awt.Color(255, 255, 255));
        txt_datafim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_datafim.setForeground(new java.awt.Color(0, 0, 0));
        txt_datafim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datafimActionPerformed(evt);
            }
        });

        txt_estimativas.setBackground(new java.awt.Color(255, 255, 255));
        txt_estimativas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_estimativas.setForeground(new java.awt.Color(0, 0, 0));
        txt_estimativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estimativasActionPerformed(evt);
            }
        });

        txt_descricao.setBackground(new java.awt.Color(255, 255, 255));
        txt_descricao.setColumns(20);
        txt_descricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_descricao.setForeground(new java.awt.Color(0, 0, 0));
        txt_descricao.setRows(5);
        jScrollPane2.setViewportView(txt_descricao);

        txt_particpantes.setBackground(new java.awt.Color(255, 255, 255));
        txt_particpantes.setColumns(20);
        txt_particpantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_particpantes.setForeground(new java.awt.Color(0, 0, 0));
        txt_particpantes.setRows(5);
        jScrollPane3.setViewportView(txt_particpantes);

        bt_salvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_salvar.setForeground(new java.awt.Color(255, 255, 255));
        bt_salvar.setText("SALVAR");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_sair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_sair.setForeground(new java.awt.Color(255, 255, 255));
        bt_sair.setText("SAIR");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CADASTRO DE PROJETOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_DataFim)
                                    .addComponent(l_DataInicio)
                                    .addComponent(l_Participantes)
                                    .addComponent(l_Descricao)
                                    .addComponent(l_Titulo))
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(l_Estimativas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_datainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_datafim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_estimativas, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_salvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt_sair)))
                                .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel7)))
                .addContainerGap(746, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_Descricao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_Participantes)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_datainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_DataInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_datafim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_DataFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_estimativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Estimativas))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvar)
                    .addComponent(bt_sair))
                .addContainerGap(847, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void txt_datainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datainicioActionPerformed

    private void txt_datafimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datafimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datafimActionPerformed

    private void txt_estimativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estimativasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estimativasActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        try {
            
            String titulo = txt_titulo.getText();
            String descricao = txt_descricao.getText();
            String parcipantes = txt_particpantes.getText();
            String datainicio = txt_datainicio.getText();
            String datafim = txt_datafim.getText();
            String estimativas = txt_estimativas.getText();
                    

            ProjetosController projeto = new ProjetosController();

            projeto.salvar(titulo, descricao, parcipantes, datainicio, datafim, estimativas);
            
        } catch (Exception e) {
            System.out.println("Erro" + e.getMessage());
        }
    }//GEN-LAST:event_bt_salvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_sair;
    private javax.swing.JToggleButton bt_salvar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l_DataFim;
    private javax.swing.JLabel l_DataInicio;
    private javax.swing.JLabel l_Descricao;
    private javax.swing.JLabel l_Estimativas;
    private javax.swing.JLabel l_Participantes;
    private javax.swing.JLabel l_Titulo;
    private javax.swing.JTextField txt_datafim;
    private javax.swing.JTextField txt_datainicio;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JTextField txt_estimativas;
    private javax.swing.JTextArea txt_particpantes;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
