CREATE DATABASE IF NOT EXISTS DBCode;
USE DBCode;

CREATE TABLE IF NOT EXISTS `USER` (
 ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 EMAIL VARCHAR(255) NOT NULL UNIQUE,
 USERNAME VARCHAR(255) NOT NULL UNIQUE,
 PASSWORD VARCHAR(255) NOT NULL,
 RESET_CODE VARCHAR(20),
 PROFILE VARCHAR(255) NOT NULL,
 RESET_CODE VARCHAR(12),
INDEX IDX_EMAIL(EMAIL),
INDEX IDX_USERNAME(USERNAME)

    );