/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.dombosco.dbcode.accessManagment.view;

/**
 *
 * @author fabio
 */
public class recuperacao extends javax.swing.JFrame {

    /**
     * Creates new form recupera��o
     */
    public recuperacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        replyPassword = new javax.swing.JTextField();
        sendCode = new javax.swing.JButton();
        savePassword = new javax.swing.JButton();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 650));
        setResizable(false);

        panel.setLayout(null);

        email.setText("Digite seu email cadastrado");
        panel.add(email);
        email.setBounds(330, 140, 190, 22);

        code.setText("Digite o c�digo recebido");
        panel.add(code);
        code.setBounds(330, 230, 190, 22);

        password.setText("Digite a nova senha");
        panel.add(password);
        password.setBounds(330, 320, 190, 22);

        replyPassword.setText("Repita a nova senha");
        panel.add(replyPassword);
        replyPassword.setBounds(330, 370, 190, 22);

        sendCode.setText("Enviar c�digo");
        panel.add(sendCode);
        sendCode.setBounds(360, 430, 130, 23);

        savePassword.setText("Cadastrar Senha");
        panel.add(savePassword);
        savePassword.setBounds(360, 470, 130, 23);

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO_INICIAL_FORMATED-fotor-20231103211254.png"))); // NOI18N
        panel.add(Image);
        Image.setBounds(0, 0, 600, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recuperacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JTextField code;
    private javax.swing.JTextField email;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField password;
    private javax.swing.JTextField replyPassword;
    private javax.swing.JButton savePassword;
    private javax.swing.JButton sendCode;
    // End of variables declaration//GEN-END:variables
}
